apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-signed-images-audit
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-signed-by-github
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "910321623036.dkr.ecr.ap-south-1.amazonaws.com/*"
          attestors:
            - entries:
                - keyless:
                    subject: "https://github.com/Akashoistec/secure-supply-chain-demo-app/.github/workflows/build-sign-push.yml@refs/heads/main"
                    issuer: "https://token.actions.githubusercontent.com"
